# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DefiPrime.com
#email: youremailaddress@gmail.com
description: List of the best Decentralized Finance Products
#baseurl: "https://defiprime.com" # the subpath of your site, e.g. /blog
url: "https://defiprime.com" # the base hostname & protocol for your site

# Logo settings
logo-image-url: favicon.png
#font-awesome-icon-logo: fas fa-dice-d20

toc:
  min_level: 1 # default: 1
  max_level: 2 # default: 6

pagination:
  enabled: true
  per_page: 8
  permalink: '/page/:num/'
  title: 'DeFi blog - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Build settings
markdown: kramdown
# Layout settings
home-link-in-menu: no
plugins:
  - jekyll-random
include: ['.htaccess']
collections_dir: collections
collections:
  - lending
  - derivatives
  - analytics
  - assets-managament-tools
  - exchanges
  - infrastructure
  - insurance
  - assets-tokenization
  - kyc_identity
  - marketplaces
  - prediction_markets
  - stablecoins
  - margin-trading
  - events
  - payments
  - staking

exclude: [node_modules, README.md, CONTRIBUTING.md]
keep_files: [images]
sass:
    style: compressed
