# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DefiPrime.com
#email: youremailaddress@gmail.com
description: List of the best Decentralized Finance Products 
#baseurl: "/phantom-jekyll-theme" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site

# Logo settings
logo-image-url: favicon.png
#font-awesome-icon-logo: fas fa-dice-d20

# Social settings


# Build settings
markdown: kramdown
# Layout settings
home-link-in-menu: no
plugins:
  - jekyll-seo-tag
  - jekyll-last-modified-at
  - jekyll-random
