---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: jekyll-posts
  label: Posts
  create: documents
- type: jekyll-pages
  label: Pages
  create: all
- type: directory
  path: _dao
  label: Dao
  create: all
  match: "**/*"
- type: directory
  path: _staking
  label: Staking
  create: all
  match: "**/*"
- type: directory
  path: _payments
  label: Payments
  create: all
  match: "**/*"
- type: directory
  path: _events
  label: Events
  create: all
  match: "**/*"
- type: directory
  path: _margin-trading
  label: Margin trading
  create: all
  match: "**/*"
- type: directory
  path: _stablecoins
  label: Stablecoins
  create: all
  match: "**/*"
- type: directory
  path: _prediction_markets
  label: Prediction markets
  create: all
  match: "**/*"
- type: directory
  path: _marketplaces
  label: Marketplaces
  create: all
  match: "**/*"
- type: directory
  path: _kyc_identity
  label: Kyc identity
  create: all
  match: "**/*"
- type: directory
  path: _assets-tokenization
  label: Assets tokenization
  create: all
  match: "**/*"
- type: directory
  path: _insurance
  label: Insurance
  create: all
  match: "**/*"
- type: directory
  path: _infrastructure
  label: Infrastructure
  create: all
  match: "**/*"
- type: directory
  path: _exchanges
  label: Exchanges
  create: all
  match: "**/*"
- type: directory
  path: _assets-management-tools
  label: Assets management tools
  create: all
  match: "**/*"
- type: directory
  path: _analytics
  label: Analytics
  create: all
  match: "**/*"
- type: directory
  path: _derivatives
  label: Derivatives
  create: all
  match: "**/*"
- type: directory
  path: _lending
  label: Lending
  create: all
  match: "**/*"
upload_dir: images/blog
public_path: "/images/blog"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
